### ISSUE TITLE
[Feature] Update user screens to reduce number of clicks

### ISSUE THREAD

**Issue by justbuildstuff-dev** [justbuildstuff-dev/Fitness-App#53]
## Overview
Currently to check off a set you need to:
- Choose the program
- Choose the week
- Choose the workout
- Choose the exercise
- Then check the set

I would like to remove some of the screens and condense the content. The update should make it so that when a user selects the workout, they are taken to a workout screen that displays the exercises for that workout and the associated sets. The following screen shot shows roughly the idea however this should be adapted to align with our design standards.

<img width="572" height="1270" alt="Image" src="https://github.com/user-attachments/assets/14ac96d7-f21f-4bd8-9863-c2bd9c812f31" />

When a user creates a new workout, they are still taken to the workout details screen and asked to create an exercise. When they create that exercise they should be asked how many sets are required for that exercise and on confirmation each of those set objects should be created in the database.

We could have the "set row" contain:
- the weight
- the reps
- a checkbox for the set
- a notes button that would give them the ability to track rest times and notes
- a delete button
- a add set button (this would create a new set for the exercise where the button was pressed)

## Requirements
**Notion PRD:** https://www.notion.so/Consolidated-Workout-Screen-Reduce-Navigation-Clicks-294879be578981afa511dfba666098b8

**Technical Design:** [Consolidated_Workout_Screen_Technical_Design.md](https://github.com/justbuildstuff-dev/Fitness-App/blob/main/Docs/Technical_Designs/Consolidated_Workout_Screen_Technical_Design.md)

## User Stories
- As a user tracking my workout, I want to see all exercises and sets for a workout on one screen, so that I can quickly check off sets without navigating through multiple screens.
- As a user creating a new exercise, I want to specify the number of sets upfront, so that all my sets are created at once and I don't have to manually add them one by one.
- As a user during my workout, I want to quickly add an additional set to an exercise, so that I can adjust my workout on the fly without leaving the screen.
- As a user tracking rest times, I want to add notes and rest time to each set via a modal, so that I can keep detailed records without cluttering the main workout screen.
- As a user who completes a set, I want my set data to be locked and saved immediately, so that I don't accidentally modify completed sets.
- As a user organizing my workout, I want to reorder exercises within a workout, so that I can sequence exercises in my preferred training order.

## Implementation Tasks

**Total Estimated Effort:** 34 hours

### UI Components (15 hours)
- #113: Create ConsolidatedWorkoutScreen UI Structure (4h)
- #114: Implement SetRow Widget with Inline Editing (5h)
- #115: Implement ExerciseCard Widget with Reordering (6h)

### Exercise Creation & Navigation (5 hours)
- #116: Implement Create Exercise Flow with Set Count Stepper (3h)
- #117: Update Navigation and Routing to ConsolidatedWorkoutScreen (2h)

### Data & Testing (14 hours)
- #118: Implement Data Loading and State Management for Consolidated Screen (4h)
- #119: Write Tests for Consolidated Workout Screen (6h)
- #120: Manual Testing and Documentation for Consolidated Workout Screen (4h)

### Consolidated Workout Screen
- [ ] Selecting a workout displays all exercises and sets on one screen
- [ ] Workout name displayed at top of screen
- [ ] Back button navigates to Week screen
- [ ] Empty state shows 'Create First Exercise' button

### Exercise Cards
- [ ] Each exercise displayed as card with nested sets
- [ ] Exercise name shown at top of card
- [ ] 'Add Set' button visible next to exercise name (max 10 sets enforced)
- [ ] 3-dot menu provides Edit Name and Delete Exercise options
- [ ] Exercises can be reordered via drag handle

### Set Rows
- [ ] Fields displayed based on exercise type (strength, cardio, bodyweight, custom)
- [ ] Checkbox marks set as complete, making fields read-only
- [ ] NO strikethrough or color change on completion (fixes bug #51)
- [ ] Notes button opens modal with text field (250 char limit) and rest time picker
- [ ] Delete button requires confirmation; prevents deletion of last set

### Exercise Creation
- [ ] Modal opens with exercise name, type selector, and sets stepper (default 1, max 10)
- [ ] All specified sets created in Firestore on confirmation
- [ ] User returns to workout screen with new exercise visible

### Data Persistence
- [ ] Completed sets persist immediately to Firestore
- [ ] Completed status remains until manually unchecked
- [ ] Exercise deletion cascades to all sets and analytics data

## Technical Notes
- Remove/deprecate separate Exercise Details screen (currently navigates Program > Week > Workout > Exercise)
- Consolidate to 3-screen navigation: Program > Week > Workout (with exercises/sets shown)
- Ensure Firestore queries efficiently load all exercises + sets for a workout
- Balance performance with usability - consider pagination/lazy loading if workout has 10+ exercises
- Maintain existing Firestore hierarchy: users/{userId}/programs/{programId}/weeks/{weekId}/workouts/{workoutId}/exercises/{exerciseId}/sets/{setId}
- This feature addresses bug #51 (strikethrough on completion) as part of set completion behavior redesign

## Related Issues
- Fixes #51 - Sets crossed out when completed

## Agent Workflow
- [x] Requirements complete (BA)
- [x] Design complete (SA)  
- [ ] Implementation complete (Dev)
- [ ] Testing complete (Testing)
- [ ] QA approved (QA)
- [ ] Deployed (Deployment)

**Comment by justbuildstuff-dev** [comment]
## Test Failure Update

Merged `main` into `feature/issue-53-consolidated-workout` successfully, but discovered compilation errors blocking tests.

**Bug Issue Created:** #255

**Root Cause:** Semantic merge conflict - `loadAllWorkoutSets()` method references removed `_error` field

**Status:** Handing off to Developer Agent for quick fix (3 lines)

**CI Run:** https://github.com/justbuildstuff-dev/Fitness-App/actions/runs/20672083392

**Comment by justbuildstuff-dev** [comment]
## Test Failures Discovered

After resolving merge conflicts and compilation errors, CI revealed 27 failing widget tests + 2 functional issues.

**Bug Issue Created:** #258

**Problems:**
1. 27 widget tests fail - tests don't match current implementation
2. Permission error when adding exercises
3. Add set button doesn't work

**Status:** Compilation errors fixed (#255), but functional and test issues block QA. Handing off to Developer Agent for fixes.
